Feature
CornerstoneII/Building-with-Responsive-Design pull request #3
Opened 2020-08-17 15:13 UTC by enkog

Milestone 6: Building with Responsive Design
-Added background images
-Added responsiveness for two break points: 1024px and 768px

2020-08-18 13:27 UTC, andresporras3423 requested changes
### Status: Changes Required :recycle:
**Hello @enkog @CornerstoneII** 
Good job with your first submission for this project :muscle:  :muscle:
Your HTML code is clean and follows the requirements :clap: :clap: :clap:  
There are some details to improve before you can go ahead:
- [x] add a screeshot to the README file
- [x] For the README file follow this template: https://github.com/microverseinc/readme-template
- [x] In the style.css file, remove commented code on line 617
- [x] In the style.css file, group selectors on lines 758 and 764.
- [x] For medium and small screen size, remove horizontal scroll.
- [x]  In medium screen size, the TNW logo should disappear:

| Yours | Original |
|:---:|:---:|
|![image](https://i.imgur.com/2egVEkul.png) | ![image](https://i.imgur.com/7LUUEOTl.png) |

- [x] In medium screen size, the section after "latest funding" should be 2 columns, not three:

| Yours | Original |
|:---:|:---:|
|![image](https://i.imgur.com/HD9u5h8l.png) | ![image](https://i.imgur.com/AixP8Ktl.png) |

-  You must define the responsive behavior for the small screen size, as the original webpage:

| Yours | Original |
|:---:|:---:|
|![image](https://i.imgur.com/IAQM7grl.png) | ![image](https://i.imgur.com/Cm5r8w5l.png) |

Please request another review once you are ready! :+1: 

Happy coding :relaxed:

Oscar Andrés Russi Porras

2020-08-18 13:27 UTC, andresporras3423 commented on css/style.css
> +    /* grid-template-columns: repeat(2, 1fr); */
Remove commented code

2020-08-18 13:27 UTC, andresporras3423 commented on css/style.css
> +  }
Group selectors with the same style definition.

2020-08-19 19:01 UTC, MuriloRoque approved these changes
# Status: Approved 🟢 

![chuck](https://i.pinimg.com/originals/b9/36/d6/b936d6d6247faccc87e36d805ef60282.gif)

## Hello @enkog and @CornerstoneII 👋 

## Thank you for making all of the changes requested by the previous TSE. Congratulations, your project is approved 😄 Good luck with your next projects 🚀 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[![Twitter Follow](https://img.shields.io/twitter/follow/MuriloRoquePai1?label=Follow%20Murilo%20on%20Twitter&style=social)](https://twitter.com/MuriloRoquePai1)

2020-08-19 21:20 UTC, merged